version: '3'

services:
  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=your_password
      - MYSQL_DATABASE=lbfat
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - lbfat-network

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - lbfat-network

  emqx:
    image: emqx/emqx:4.4.19
    ports:
      - "1883:1883"
      - "8083:8083"
      - "18083:18083"
    volumes:
      - emqx_data:/opt/emqx/data
      - ./docker/emqx/emqx.conf:/opt/emqx/etc/emqx.conf
    environment:
      - EMQX_NAME=emqx
      - EMQX_HOST=127.0.0.1
    networks:
      - lbfat-network

networks:
  lbfat-network:
    driver: bridge

volumes:
  mysql_data:
  emqx_data:
