CREATE DATABASE IF NOT EXISTS lbfat DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
USE lbfat;

CREATE TABLE IF NOT EXISTS devices (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    device_code VARCHAR(32) NOT NULL COMMENT '设备编码',
    device_name VARCHAR(64) NOT NULL COMMENT '设备名称',
    status TINYINT NOT NULL DEFAULT 0 COMMENT '状态：0-离线 1-在线',
    last_online_time DATETIME COMMENT '最后在线时间',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uk_device_code (device_code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT INTO devices (device_code, device_name) VALUES ('TEST001', '测试设备1');
