version: '3'

services:
  mysql:
    image: mysql:5.7
    container_name: lbfat_mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=13701033228
      - MYSQL_DATABASE=lbfat
      - MYSQL_ROOT_HOST=%
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d
    networks:
      - lbfat_network
    command: --default-authentication-plugin=mysql_native_password
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p13701033228"]
      interval: 10s
      timeout: 5s
      retries: 3

  emqx:
    image: emqx/emqx:latest
    container_name: lbfat_emqx
    ports:
      - "1883:1883"   # MQTT
      - "8083:8083"   # WebSocket
      - "8084:8084"   # WSS
      - "8883:8883"   # MQTT SSL
      - "18083:18083" # Dashboard
    volumes:
      - ./emqx/data:/opt/emqx/data
      - ./emqx/log:/opt/emqx/log
    networks:
      - lbfat_network
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: lbfat_backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=13701033228
      - DB_NAME=lbfat
      - MQTT_HOST=emqx
      - MQTT_PORT=1883
    depends_on:
      mysql:
        condition: service_healthy
      emqx:
        condition: service_started
    networks:
      - lbfat_network
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: 256M
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 10s
      timeout: 5s
      retries: 3

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: lbfat_frontend
    ports:
      - "8080:80"
    environment:
      - VITE_API_URL=http://localhost:3000
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - lbfat_network
    volumes:
      - ./frontend:/app
      - /app/node_modules
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 128M
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 10s
      timeout: 5s
      retries: 3

#  mqtt-test:
#    build:
#      context: ./tests
#      dockerfile: Dockerfile
#    container_name: lbfat_mqtt_test
#    depends_on:
#      emqx:
#        condition: service_started
#    networks:
#      - lbfat_network
#    stdin_open: true
#    tty: true

networks:
  lbfat_network:
    driver: bridge
