version: '3.8'

services:
  mysql:
    image: mysql:5.7
    container_name: lbfat_mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=13701033228
      - MYSQL_DATABASE=lbfat
      - MYSQL_ROOT_HOST=%
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d
      - ./mysql/conf/my.cnf:/etc/mysql/conf.d/my.cnf
    networks:
      - lbfat_network
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p13701033228"]
      interval: 10s
      timeout: 5s
      retries: 3

  emqx:
    image: emqx/emqx:latest
    container_name: lbfat_emqx
    ports:
      - "1883:1883"   # MQTT
      - "8083:8083"   # WebSocket
      - "8084:8084"   # WSS
      - "8883:8883"   # MQTT SSL
      - "18083:18083" # Dashboard
    volumes:
      - ./emqx/data:/opt/emqx/data
      - ./emqx/log:/opt/emqx/log
    networks:
      - lbfat_network
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: lbfat_backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
      - DB_HOST=lbfat_mysql
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=13701033228
      - DB_NAME=lbfat
      - MQTT_HOST=lbfat_emqx
      - MQTT_PORT=1883
      - HOST_IP=${HOST_IP:-0.0.0.0}
      - CORS_ORIGIN=*
    depends_on:
      mysql:
        condition: service_healthy
      emqx:
        condition: service_started
    networks:
      - lbfat_network
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: 256M
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 10s
      timeout: 5s
      retries: 3

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: lbfat_frontend
    ports:
      - "8080:80"
    environment:
      - VITE_API_URL=/api
      - HOST_IP=${HOST_IP:-0.0.0.0}
    depends_on:
      - backend
    networks:
      - lbfat_network
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 128M

  neo4j:
    image: neo4j:5.12.0
    container_name: lbfat-neo4j
    ports:
      - "7474:7474"  # HTTP
      - "7687:7687"  # Bolt
    volumes:
      - ./neo4j/data:/data
      - ./neo4j/logs:/logs
      - ./neo4j/conf:/conf
    environment:
      - NEO4J_AUTH=neo4j/13701033228
      - NEO4J_dbms_memory_pagecache_size=1G
      - NEO4J_dbms.memory.heap.initial_size=1G
      - NEO4J_dbms_memory_heap_max__size=1G
    networks:
      - lbfat-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider localhost:7474 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  lbfat_network:
    driver: bridge
  lbfat-network:
    driver: bridge
