version: '3'

services:
  frontend:
    container_name: lbfat_frontend
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile
    ports:
      - "8082:80"
    depends_on:
      - backend
    networks:
      - lbfat-network

  backend:
    container_name: lbfat_backend
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=13701033228
      - DB_NAME=lbfat
      - MQTT_HOST=emqx
      - MQTT_PORT=1883
    depends_on:
      - mysql
      - emqx
    networks:
      - lbfat-network

  mysql:
    container_name: lbfat_mysql
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=13701033228
      - MYSQL_DATABASE=lbfat
      - MYSQL_ROOT_HOST=%
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    networks:
      - lbfat-network

  emqx:
    container_name: lbfat_emqx
    image: emqx/emqx:latest
    ports:
      - "11883:1883"   # MQTT
      - "18083:18083"  # Dashboard
      - "18084:8083"   # WebSocket
    volumes:
      - ./docker/emqx/emqx.conf:/opt/emqx/etc/emqx.conf
      - emqx_data:/opt/emqx/data
    networks:
      - lbfat-network

networks:
  lbfat-network:
    driver: bridge

volumes:
  mysql_data:
  emqx_data: 